backend:
  name: github
  repo: IceCloudPlux/IceCloudPlux.github.io
  branch: main
  base_url: "https://api.decapcms.org"
  auth_scope: repo

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "plugin_data"
    label: "插件管理"
    files:
      - name: "icecloud_list"
        label: "IceCloud 插件列表"
        file: "_data/icecloud_plugins.json"
        fields:
          - name: "plugins"
            label: "插件"
            widget: "list"
            fields:
              - { label: "插件名称", name: "title", widget: "string" }
              - { label: "版本号", name: "version", widget: "string" }
              - { label: "支持 MC 版本", name: "mc_version", widget: "string" }
              - { label: "发布日期", name: "date", widget: "date" }
              - { label: "下载链接", name: "download_url", widget: "string" }
      - name: "plux_list"
        label: "Plux 插件列表"
        file: "_data/plux_plugins.json"
        fields:
          - name: "plugins"
            label: "插件"
            widget: "list"
            fields:
              - { label: "插件名称", name: "title", widget: "string" }
              - { label: "版本号", name: "version", widget: "string" }
              - { label: "支持 MC 版本", name: "mc_version", widget: "string" }
              - { label: "发布日期", name: "date", widget: "date" }
              - { label: "下载链接", name: "download_url", widget: "string" }
